package playMachine;

public enum menu {
    READ_FILE,
    SHOW_DETAILS,
    CHOOSE_MANUAL_CONFIGURATION,
    CHOOSE_AUTO_CONFIGURATION,
    INPUT_PROCESSING,
    INIT_MACHINE,
    HISTORY_STATISTICS,
    SAVE_MACHINE_TO_FILE,
    LOAD_MACHINE_FROM_FILE,
    EXIT
}
